apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Namespace
metadata:
  name: artemis
---
apiVersion: operators.coreos.com/v1alpha1
kind: OperatorGroup
metadata:
  name: keycloak-operator-group
  namespace: keycloak
spec:
  targetNamespaces:
    - keycloak
---
apiVersion: operators.coreos.com/v1alpha1
kind: OperatorGroup
metadata:
  name: artemis-operator-group
  namespace: artemis
spec:
  targetNamespaces:
    - artemis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-operator
  template:
    metadata:
      labels:
        name: keycloak-operator
    spec:
      containers:
        - name: keycloak-operator
          image: quay.io/keycloak/keycloak-operator:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
  namespace: artemis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  template:
    metadata:
      labels:
        name: amq-broker-operator
    spec:
      containers:
        - name: amq-broker-operator
          image: quay.io/artemiscloud/amq-broker-operator:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
