apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
    generateName: windows10-installer-run-
spec:
    params:
    -   name: winImageDownloadURL
        value: https://software.download.prss.microsoft.com/dbazure/Win10_22H2_English_x64v1.iso?t=9a3933fa-b670-45dc-80f6-3c1d4438a098&P1=1743721582&P2=601&P3=2&P4=gB0Le5aruB6bpNRQWNKtzMTAabPM8gitGqI%2fSPQhjuNGRtFkHdkt43lZvN1mciPE1rHKvcLeVE8Yognh%2bkmbO5TZRH7TTOKvF5Y73n4y3L9BJQnrpuXpdzBczQu9VncfiqvhAsjnZkcDHb9CWXRxsinlx2j1IyeoKAPeWX5sKxhGnfz1Z9GEANRc1onPci3ZGIpgzLn2HDUL5nxfnA3C80IXrvcX4xhU9JW4anLQq9NM7qyQEzQSVwv76gskbODGsP1H2tbC%2f1i7HqVXahG6NRzP8FMpyVtvFN3QyCwm5EYeqpJQmmPx19xTaVYTdXynrl22O2HG8%2fE0pzeEt1xYZw%3d%3d
    -   name: acceptEula
        value: false
    -   name: preferenceName
        value: windows.10.virtio
    -   name: autounattendConfigMapName
        value: windows10-efi-autounattend
    -   name: baseDvName
        value: win10
    -   name: isoDVName
        value: win10
    pipelineRef:
        params:
        -   name: catalog
            value: redhat-pipelines
        -   name: type
            value: artifact
        -   name: kind
            value: pipeline
        -   name: name
            value: windows-efi-installer
        -   name: version
            value: v4.18.1
        resolver: hub
    taskRunSpecs:
    -   pipelineTaskName: modify-windows-iso-file
        podTemplate:
            securityContext:
                fsGroup: 107
                runAsUser: 107