apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
    generateName: windows10-installer-run-
spec:
    params:
    -   name: winImageDownloadURL
        value: https://software.download.prss.microsoft.com/dbazure/Win10_22H2_English_x64v1.iso?t=2f4514aa-f5d0-4b4a-9e7a-6a4f399764e7&P1=1743528866&P2=601&P3=2&P4=LWJeggEYd3KaANFRT58iELz1imyUj7mFVtbxyGMitkvEkyjC6mL7%2frBFUSuPDvh%2fM7BGbeaza6S8XBXynlU94atkgFSR8w4Blp2AlK2abZ6alGqRHz9h37ehFPzLcWj7HhciG7hTZ9W0K3fiwMWZQXSTqBHz6Bxm8d9uLdkxc43aDcj%2fA0Afq9IhvJZx0SFNzdeSAt6xB4iPXAhwKvtvbJWB8cqbl9bqR%2belDIvfmvNDcmqQIjzqGGFdfXooS3buaNsZIwo9UnXZVHFNTGM3PQ3EH9kk6hjE6Dj3QUczgQIVGfi%2bp95KWBwT0ILqzlLGk6IwfNPrbBGqxre8VRk1Bw%3d%3d
    -   name: acceptEula
        value: false
    -   name: preferenceName
        value: windows.10.virtio
    -   name: autounattendConfigMapName
        value: windows10-efi-autounattend
    -   name: baseDvName
        value: win10
    -   name: isoDVName
        value: win10
    pipelineRef:
        params:
        -   name: catalog
            value: redhat-pipelines
        -   name: type
            value: artifact
        -   name: kind
            value: pipeline
        -   name: name
            value: windows-efi-installer
        -   name: version
            value: v4.18.1
        resolver: hub
    taskRunSpecs:
    -   pipelineTaskName: modify-windows-iso-file
        podTemplate:
            securityContext:
                fsGroup: 107
                runAsUser: 107