- name: Provision Windows VM with Keycloak and AMQ Broker
  hosts: windows_vm
  vars:
    keycloak_version: "23.0.6"
    activemq_version: "2.31.2"
    keycloak_admin_user: "admin"
    keycloak_admin_password: "admin123"
    amq_user: "admin"
    amq_password: "admin123"
    install_dir: "C:\\Apps"

  tasks:
# Install Chocolatey
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

# Install Java via Chocolatey
    - name: Install OpenJDK 17
      win_chocolatey:
        name: openjdk
        version: "17.0.10"
        state: present

# Create install dir
    - name: Ensure installation directory exists
      win_file:
        path: "{{ install_dir }}"
        state: directory
    
# Keycloak

# Install AMQ Broker Artemis
    - name: Download ActiveMQ Artemis
      win_get_url:
        url: "https://archive.apache.org/dist/activemq/activemq-artemis/{{ activemq_version }}/apache-artemis-{{ activemq_version }}-bin.zip"
        dest: "C:\\Temp\\apache-artemis-{{ activemq_version }}-bin.zip"

    - name: Extract ActiveMQ Artemis
      win_unzip:
        src: "C:\\Temp\\apache-artemis-{{ activemq_version }}-bin.zip"
        dest: "{{ install_dir }}\\apache-artemis-{{ activemq_version }}"

    - name: Rename ActiveMQ Artemis directory
      win_command: "ren {{ install_dir }}\\apache-artemis-{{ activemq_version }} amq-broker"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}\\amq-broker"

    - name: Create AMQ Broker instance
      win_shell: |
        cd "{{ install_dir }}\\amq-broker\\bin"
        artemis.cmd create --user {{ amq_user }} --password {{ amq_password }} --allow-anonymous "{{ install_dir }}\\amq-broker\\instance"
      args:
        creates: "{{ install_dir }}\\amq-broker\\instance"

# Config Step
    - name: Create AMQ Broker startup script
      win_file:
        path: "{{ install_dir }}\\amq-broker\\start-amq.bat"
        state: touch

    - name: Configure AMQ Broker startup script
      win_copy:
        dest: "{{ install_dir }}\\amq-broker\\start-amq.bat"
        content: |
          @echo off
          set "AMQ_HOME={{ install_dir }}\\amq-broker\\instance"
          cd /d "%AMQ_HOME%\bin"
          artemis.cmd run
        mode: '0755'

    - name: Register AMQ Broker as a Windows service
      win_nssm:
        name: "AMQBroker"
        application: "{{ install_dir }}\\amq-broker\\start-amq.bat"
        start_mode: auto
        state: present

    - name: Start AMQ Broker service
      win_service:
        name: "AMQBroker"
        state: started

# Cleanup
    - name: Remove downloaded archives
      win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - "C:\\Temp\\keycloak-{{ keycloak_version }}.zip"
        - "C:\\Temp\\apache-artemis-{{ activemq_version }}-bin.zip"
